# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cameronbarrett/lab3_retry/lab3_retry.srcs/sources_1/bd/jtag_spi_ila/ip/jtag_spi_ila_clk_wiz_0/jtag_spi_ila_clk_wiz_0.xci
# IP: The module: 'jtag_spi_ila_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cameronbarrett/lab3_retry/lab3_retry.gen/sources_1/bd/jtag_spi_ila/ip/jtag_spi_ila_clk_wiz_0/jtag_spi_ila_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_spi_ila_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/cameronbarrett/lab3_retry/lab3_retry.gen/sources_1/bd/jtag_spi_ila/ip/jtag_spi_ila_clk_wiz_0/jtag_spi_ila_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_spi_ila_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/cameronbarrett/lab3_retry/lab3_retry.gen/sources_1/bd/jtag_spi_ila/ip/jtag_spi_ila_clk_wiz_0/jtag_spi_ila_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_spi_ila_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/cameronbarrett/lab3_retry/lab3_retry.srcs/sources_1/bd/jtag_spi_ila/ip/jtag_spi_ila_clk_wiz_0/jtag_spi_ila_clk_wiz_0.xci
# IP: The module: 'jtag_spi_ila_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cameronbarrett/lab3_retry/lab3_retry.gen/sources_1/bd/jtag_spi_ila/ip/jtag_spi_ila_clk_wiz_0/jtag_spi_ila_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_spi_ila_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/cameronbarrett/lab3_retry/lab3_retry.gen/sources_1/bd/jtag_spi_ila/ip/jtag_spi_ila_clk_wiz_0/jtag_spi_ila_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_spi_ila_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/cameronbarrett/lab3_retry/lab3_retry.gen/sources_1/bd/jtag_spi_ila/ip/jtag_spi_ila_clk_wiz_0/jtag_spi_ila_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_spi_ila_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
