# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/jtag_spi_ila/jtag_spi_ila.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag_spi_ila || ORIG_REF_NAME==jtag_spi_ila} -quiet] -quiet

# IP: bd/jtag_spi_ila/ip/jtag_spi_ila_jtag_axi_0_0/jtag_spi_ila_jtag_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag_spi_ila_jtag_axi_0_0 || ORIG_REF_NAME==jtag_spi_ila_jtag_axi_0_0} -quiet] -quiet

# IP: bd/jtag_spi_ila/ip/jtag_spi_ila_axi_quad_spi_0_0/jtag_spi_ila_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag_spi_ila_axi_quad_spi_0_0 || ORIG_REF_NAME==jtag_spi_ila_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/jtag_spi_ila/ip/jtag_spi_ila_clk_wiz_0/jtag_spi_ila_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag_spi_ila_clk_wiz_0 || ORIG_REF_NAME==jtag_spi_ila_clk_wiz_0} -quiet] -quiet

# IP: bd/jtag_spi_ila/ip/jtag_spi_ila_rst_clk_wiz_100M_0/jtag_spi_ila_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag_spi_ila_rst_clk_wiz_100M_0 || ORIG_REF_NAME==jtag_spi_ila_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/jtag_spi_ila/ip/jtag_spi_ila_reset_inv_0_0/jtag_spi_ila_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag_spi_ila_reset_inv_0_0 || ORIG_REF_NAME==jtag_spi_ila_reset_inv_0_0} -quiet] -quiet

# IP: bd/jtag_spi_ila/ip/jtag_spi_ila_system_ila_0_0/jtag_spi_ila_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag_spi_ila_system_ila_0_0 || ORIG_REF_NAME==jtag_spi_ila_system_ila_0_0} -quiet] -quiet

# XDC: /home/cameronbarrett/lab3_retry/lab3_retry.gen/sources_1/bd/jtag_spi_ila/jtag_spi_ila_ooc.xdc
